"use client";

import Image from "next/image";
import { useState } from "react";

type DocFile = {
  name: string;
  url: string;
};

type ProjectItem = {
  title: string;
  company?: string;
  desc: string;
  medias: string[];
  docs?: DocFile[];
  demoUrl?: string;
};

export default function Project() {
  const [tab, setTab] = useState<"qa" | "web">("qa");
  const [videoSrc, setVideoSrc] = useState<string | null>(null);
  const [docs, setDocs] = useState<DocFile[] | null>(null);

  const openVideo = (src: string) => setVideoSrc(src);
  const closeVideo = () => setVideoSrc(null);
  const closeDocs = () => setDocs(null);
  const qaProjects: ProjectItem[] = [
    {
      title: "Kopra AI Trader",
      company: "PT Bank Mandiri Tbk",
      desc: "Kopra AI Trader is a banking service project provided by a bank for large companies, institutions, governments, and other corporate clients. Here, I act as Quality Assurance, executing 20 test cases daily and creating efficient test case results. I use Jira as a monitoring tool to ensure the Kopra AI Trader project runs smoothly without bugs. In the Kopra AI Trader project, I check the LC Number and Supporting Documents generated by the AI",
      medias: ["/excetue tc regresi.png"],
      docs: [
        { name: "Effiendt Kopra AI Trader", url: "/KP-479311.pdf" },
        { name: "Kopra Regression Report.docx", url: "/KP-479312.pdf" },
      ],
    },
    {
      title: "Dee E-Commerance",
      company: "PT Berkah Digital Aisah",
      desc: "Project Dee is a marketplace platform for domain registration that produces websites and mobile apps for customer transactions. My role as Quality Assurance (QA) includes developing test plans, creating test scenarios and test cases for websites and mobile devices, conducting manual UAT and regression testing, and compiling bug reports via Google Docs as a communication tool with developers.",
      medias: [
        "/WhatsApp Image 2025-12-31 at 00.22.06.jpeg",
        "/WhatsApp Image 2025-12-31 at 00.22.09.jpeg",
        "/WhatsApp Video 2025-12-31 at 00.21.04.mp4",
        "/WhatsApp Video 2025-12-31 at 00.22.08.mp4",
        "/WhatsApp Video 2025-12-31 at 00.22.09.mp4",
      ],
      docs: [
        { name: "TC Admin Dee", url: "/TC ADMIN DEE.xlsx" },
        {
          name: "Bagloog Dee  - Website",
          url: "https://docs.google.com/document/d/16Paq4ZvlWbqSdXFeKiIBLHwk6vomANrs/edit?usp=sharing",
        },
        {
          name: "Bagloog Dee - Mobile",
          url: "https://docs.google.com/document/d/18bpkCaHlla_PioqvOgamUysJHhjWOHlS/edit?usp=sharing",
        },
      ],
    },
    {
      title:
        "Tracer Study, Hub Arkatama & Siakad Link by Arkatama – Test Case, Backlog, Automation Testing",
      company: "PT Arkatama Multi Solusindo",
      desc: "As a Quality Assurance officer, I was involved in various projects such as Tracer Study, Siakad Link, and Hub Arkatama. I created test cases and test scenarios, and also reported bugs using Treelo and Google Docs to communicate with developers. I also learned about test automation using Selenium and API Testing.",
      medias: [
        "/landingpage.png",
        "/automationtesting.mp4",
        "/Screenshot2025-12-30-132640.png",
        "/Screenshot2025-12-30-132559.png.png",
      ],
      docs: [
        {
          name: "Hub Arkatama Testcase.xlsx",
          url: "https://docs.google.com/spreadsheets/d/1_2yIzePAwOERMi_KJ7ShdHKkRotKaP3I/edit?usp=sharing",
        },
        {
          name: "Siakad Link Testcase.xlsx",
          url: "https://docs.google.com/spreadsheets/d/1rROC68ORbsptVdqKLnXbMUiakytmas7P/edit?usp=sharing",
        },
        {
          name: "Report Bug Tracer Study",
          url: "https://docs.google.com/document/d/1QEUegHa7WJWoIWgo5zTh9m7plSWPGnSp/edit?usp=sharing",
        },
        {
          name: "Monitoring Tracer Study.xlsx",
          url: "https://docs.google.com/spreadsheets/d/10IDov2xeCWC8e8zFAHnHE5iL4S6IPtttqKBhRd2z0FE/edit?usp=sharing",
        },
        {
          name: "Report Bug Tanes.id",
          url: "https://docs.google.com/document/d/1Wz4sTogsJ55Tay7bk--uvYiy8Fikn4TFYuSKGXmNhRQ/edit?usp=sharing",
        },
        {
          name: "Report Bug Hub Arkatama",
          url: "https://docs.google.com/document/d/1QPdueJuaM4U7s2a6Gu_bfhQt_IOtw2mG/edit?usp=sharing",
        },
        {
          name: "Self Learning Katalon",
          url: "https://drive.google.com/file/d/12ncUUumKeb3djxy6V1QdFlJi7JFYqYEt/view",
        },
      ],
    },
  ];
  const webProjects: ProjectItem[] = [
    {
      title: "Migan Data Operation",
      company: "Freelancer",
      desc: "Migan Data Operation is a website for manufacturing record-keeping, making it easier for the Production Supervisor (SPV), Production Team, Quality Control (QC) team, and Quality Control Supervisor (SPV) to monitor goods and view inspection history. Previously, the paper-based process was hampered by the problem, but this system makes things easier for the team. This project was built using React JS and Flask.",
      medias: ["/Screenshot 2025-12-31 003800.png"],
      demoUrl: "https://migandataoperation.rezacode.my.id/",
    },
  ];

  const list = tab === "qa" ? qaProjects : webProjects;

  return (
    <section id="project" className="py-12 px-6 md:px-16 rpx-dot-bg">
      <h2 className="text-3xl font-bold text-center text-indigo-900 mb-6">
        My Projects
      </h2>

      {/* TAB SWITCH */}
      <div className="flex justify-center gap-3 mb-8">
        <button
          onClick={() => setTab("qa")}
          className={`px-4 py-2 rounded-lg font-medium ${
            tab === "qa"
              ? "bg-indigo-900 text-white"
              : "bg-gray-200 text-gray-500"
          }`}
        >
          Quality Assurance
        </button>

        <button
          onClick={() => setTab("web")}
          className={`px-4 py-2 rounded-lg font-medium ${
            tab === "web"
              ? "bg-indigo-900 text-white"
              : "bg-gray-200 text-gray-500"
          }`}
        >
          Full Stack Web Developer
        </button>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        {list.map((p, i) => (
          <ProjectCard
            key={i}
            project={p}
            onOpenVideo={openVideo}
            onOpenDocs={setDocs}
          />
        ))}
      </div>
      {videoSrc && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl w-[90%] md:w-[60%] max-h-[90vh] overflow-y-auto">
            <div className="p-4">
              <video
                src={videoSrc}
                controls
                autoPlay
                className="w-full max-h-[75vh] object-contain rounded-lg bg-black"
              />
              <button
                onClick={closeVideo}
                className="mt-3 w-full bg-indigo-900 text-white py-2 rounded-lg"
              >
                Tutup Video
              </button>
            </div>
          </div>
        </div>
      )}
      {docs && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-6 w-[90%] md:w-[50%]">
            <h3 className="text-lg font-bold mb-3 text-cyan-950">
              Dokumentasi QA
            </h3>

            <ul className="list-disc pl-6 mb-4">
              {docs.map((f, i) => (
                <li key={i}>
                  <a
                    href={f.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-indigo-700 underline"
                  >
                    {f.name}
                  </a>
                </li>
              ))}
            </ul>

            <button
              onClick={closeDocs}
              className="w-full bg-indigo-900 text-white py-2 rounded-lg"
            >
              Tutup
            </button>
          </div>
        </div>
      )}
    </section>
  );
}

function ProjectCard({
  project,
  onOpenVideo,
  onOpenDocs,
}: {
  project: ProjectItem;
  onOpenVideo: (src: string) => void;
  onOpenDocs: (docs: DocFile[]) => void;
}) {
  const [index, setIndex] = useState(0);

  const total = project.medias.length;
  const media = project.medias[index];

  const isVideo = (file: string) =>
    file.endsWith(".mp4") || file.endsWith(".webm");

  const next = () => setIndex((i) => (i === total - 1 ? 0 : i + 1));
  const prev = () => setIndex((i) => (i === 0 ? total - 1 : i - 1));

  return (
    <div className="border rounded-xl p-5 shadow-sm bg-white hover:shadow-md transition">
      <div className="relative mb-3">
        {isVideo(media) ? (
          <div
            className="relative cursor-pointer"
            onClick={() => onOpenVideo(media)}
          >
            <video
              src={media}
              className="rounded-lg w-full h-[280px] object-cover bg-black"
            />

            <div className="absolute inset-0 flex items-center justify-center">
              <span className="bg-amber-400 px-4 py-2 rounded-lg font-semibold">
                ▶ Play Video
              </span>
            </div>
          </div>
        ) : (
          <Image
            src={media}
            alt={project.title}
            width={500}
            height={300}
            className="rounded-lg w-full h-[280px] object-cover"
          />
        )}

        <button
          onClick={prev}
          className="absolute left-2 top-1/2 -translate-y-1/2 bg-black px-2 py-1 rounded-lg"
        >
          ‹
        </button>

        <button
          onClick={next}
          className="absolute right-2 top-1/2 -translate-y-1/2 bg-black px-2 py-1 rounded-lg"
        >
          ›
        </button>
      </div>

      <h3 className="text-cyan-800 font-semibold text-lg">
        {project.title}
      </h3>

      {project.company && (
        <p className="text-indigo-600 text-sm">{project.company}</p>
      )}

      <p className="text-gray-600 mt-2">{project.desc}</p>
      {project.docs && (
        <button
          onClick={() => onOpenDocs(project.docs!)}
          className="mt-3 w-full bg-indigo-900 text-white py-2 rounded-lg"
        >
          Lihat Dokumentasi QA
        </button>
      )}
      {project.demoUrl && (
        <a
          href={project.demoUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="mt-3 w-full block text-center bg-emerald-600 hover:bg-emerald-700 text-white py-2 rounded-lg transition"
        >
          Live Demo
        </a>
      )}
    </div>
  );
}
